import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export default async function RoleEditor({params}:{params:Promise<{roleId:string}>}) {
 const {roleId}=await params; const db=await createClient();
 const {data:role}=await db.from("organization_roles").select("id,name,description,hierarchy_level,parent_role_id,enabled,department_id").eq("id",roleId).maybeSingle();
 const {data:permissions}=await db.from("permissions").select("key,name,description,category").order("category").order("name");
 const {data:assigned}=await db.from("role_permissions").select("permission_key").eq("role_id",roleId);
 const selected=new Set((assigned??[]).map(x=>x.permission_key));
 return <main className="cad-app"><aside className="sidebar"><Link href="/staff" className="cad-brand"><strong>KIWI</strong><span>CAD</span></Link><div className="server-chip"><span className="online-dot"/><div><small>SERVER</small><b>SeasideRP</b></div></div><p className="side-label">STAFF</p><nav className="side-nav"><Link href="/staff" className="side-link"><i>◆</i><span>Staff</span></Link><Link href="/staff/roles" className="side-link active"><i>◆</i><span>Roles & Permissions</span></Link><Link href="/staff/logs" className="side-link"><i>▤</i><span>Audit Logs</span></Link></nav></aside><section className="workspace"><header className="workspace-top"><div><span className="crumb">KIWI CAD / SEASIDERP / STAFF / ROLES</span><h1>{role?.name ?? "Role"}</h1></div><Link href="/staff/roles" className="profile-button">Back</Link></header><div className="content"><section className="panel"><div className="panel-head"><div><span className="panel-kicker">ROLE</span><h3>{role?.description || "Organization role"}</h3></div><span className="badge green">LEVEL {role?.hierarchy_level ?? 0}</span></div><div className="quick-list">{permissions?.map((p:any)=><div key={p.key} style={{display:"flex",justifyContent:"space-between",gap:20,padding:"13px 0",borderBottom:"1px solid rgba(255,255,255,.06)"}}><div><b>{p.name}</b><small style={{display:"block"}}>{p.category} · {p.key}</small></div><span className="badge">{selected.has(p.key)?"GRANTED":"INHERITED / NOT DIRECT"}</span></div>)}</div><p className="info-copy">This page is read-only until the role editor actions are connected to a server action. Permission checks are enforced in Supabase rather than by hiding UI elements.</p></section></div></section></main>;
}