import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { updateRole, setRolePermissions } from "../actions";

export default async function RoleEditor({params}:{params:Promise<{roleId:string}>}) {
 const {roleId}=await params; const db=await createClient();
 const {data:role}=await db.from("organization_roles").select("id,organization_id,name,description,hierarchy_level,parent_role_id,enabled,department_id").eq("id",roleId).maybeSingle();
 const {data:roles}=role?await db.from("organization_roles").select("id,name,hierarchy_level").eq("organization_id",role.organization_id).neq("id",roleId).order("hierarchy_level",{ascending:false}):{data:[]};
 const {data:permissions}=await db.from("permissions").select("key,name,description,category").order("category").order("name");
 const {data:assigned}=await db.from("role_permissions").select("permission_key").eq("role_id",roleId);
 const selected=new Set((assigned??[]).map(x=>x.permission_key));
 if(!role) return <main className="content"><h1>Role not found</h1></main>;
 return <main className="cad-app"><aside className="sidebar"><Link href="/staff" className="cad-brand"><strong>KIWI</strong><span>CAD</span></Link><div className="server-chip"><span className="online-dot"/><div><small>SERVER</small><b>SeasideRP</b></div></div><p className="side-label">STAFF</p><nav className="side-nav"><Link href="/staff" className="side-link"><i>◆</i><span>Staff</span></Link><Link href="/staff/roles" className="side-link active"><i>◆</i><span>Roles & Permissions</span></Link><Link href="/staff/logs" className="side-link"><i>▤</i><span>Audit Logs</span></Link></nav></aside><section className="workspace"><header className="workspace-top"><div><span className="crumb">KIWI CAD / SEASIDERP / STAFF / ROLES</span><h1>{role.name}</h1></div><Link href="/staff/roles" className="profile-button">Back</Link></header><div className="content">
<section className="panel"><div className="panel-head"><div><span className="panel-kicker">ROLE SETTINGS</span><h3>Edit role</h3></div></div>
<form action={updateRole} style={{display:"grid",gap:12,maxWidth:720}}><input type="hidden" name="roleId" value={role.id}/><input name="name" defaultValue={role.name} required/><textarea name="description" defaultValue={role.description??""}/><input name="hierarchyLevel" type="number" min="0" defaultValue={role.hierarchy_level}/><select name="parentRoleId" defaultValue={role.parent_role_id??""}><option value="">No parent role</option>{roles?.map((r:any)=><option key={r.id} value={r.id}>{r.name} · Level {r.hierarchy_level}</option>)}</select><label><input type="checkbox" name="enabled" defaultChecked={role.enabled}/> Enabled</label><button className="primary-button" type="submit">Save role</button></form></section>
<section className="panel"><div className="panel-head"><div><span className="panel-kicker">PERMISSIONS</span><h3>Direct permissions</h3></div><span className="badge green">{selected.size} GRANTED</span></div>
<form action={setRolePermissions}><input type="hidden" name="roleId" value={role.id}/><div className="quick-list">{permissions?.map((p:any)=><label key={p.key} style={{display:"flex",justifyContent:"space-between",gap:20,padding:"13px 0",borderBottom:"1px solid rgba(255,255,255,.06)",cursor:"pointer"}}><div><b>{p.name}</b><small style={{display:"block"}}>{p.category} · {p.key}</small></div><input type="checkbox" name="permission" value={p.key} defaultChecked={selected.has(p.key)}/></label>)}</div><button className="primary-button" type="submit" style={{marginTop:16}}>Save permissions</button></form><p className="info-copy">Inherited permissions come from the selected parent role and are resolved server-side.</p></section>
</div></section></main>;
}