"use server";
import {createClient} from "@/lib/supabase/server";
import {revalidatePath} from "next/cache";
const ORG_SLUG="seaside-rp";
async function orgId(){const db=await createClient();const {data}=await db.from("organizations").select("id").eq("slug",ORG_SLUG).single();if(!data)throw new Error("Organization not found.");return data.id;}
export async function buyProperty(formData:FormData){const db=await createClient();const id=await orgId();const {error}=await db.rpc("purchase_property",{target_org:id,target_property:String(formData.get("propertyId")||"")});if(error)throw new Error(error.message);revalidatePath("/market");revalidatePath("/phone");}
export async function buyBusiness(formData:FormData){const db=await createClient();const id=await orgId();const {error}=await db.rpc("purchase_business",{target_org:id,target_business:String(formData.get("businessId")||"")});if(error)throw new Error(error.message);revalidatePath("/market");revalidatePath("/businesses");}
export async function createProperty(formData:FormData){const db=await createClient();const id=await orgId();const name=String(formData.get("name")||"").trim();const price=Math.round(Number(formData.get("price")||0)*100);if(!name||price<0)throw new Error("Name and valid price required.");const {data,error}=await db.from("properties").insert({organization_id:id,property_type:String(formData.get("type")||"land"),name,address:String(formData.get("address")||"").trim()||null,description:String(formData.get("description")||"").trim()||null,price_cents:price,status:"available"}).select("id").single();if(error)throw new Error(error.message);await db.rpc("record_audit_log",{target_org:id,action_name:"property.created",category_name:"commerce",target_type_name:"property",target_id_value:data.id,target_label_value:name});revalidatePath("/market");}
export async function createBusiness(formData:FormData){const db=await createClient();const id=await orgId();const {data:{user}}=await db.auth.getUser();if(!user)throw new Error("Sign in first.");const name=String(formData.get("name")||"").trim();if(!name)throw new Error("Business name is required.");const {data,error}=await db.from("businesses").insert({organization_id:id,owner_user_id:user.id,name,business_type:String(formData.get("type")||"shop"),description:String(formData.get("description")||"").trim()||null,address:String(formData.get("address")||"").trim()||null,status:"active"}).select("id").single();if(error)throw new Error(error.message);await db.rpc("record_audit_log",{target_org:id,action_name:"business.created",category_name:"commerce",target_type_name:"business",target_id_value:data.id,target_label_value:name});revalidatePath("/businesses");revalidatePath("/market");}
export async function listBusiness(formData:FormData){const db=await createClient();const id=await orgId();const {data:{user}}=await db.auth.getUser();if(!user)throw new Error("Sign in first.");const businessId=String(formData.get("businessId")||"");const price=Math.round(Number(formData.get("price")||0)*100);if(!businessId||price<=0)throw new Error("Business and sale price are required.");const {error}=await db.from("businesses").update({status:"for_sale",sale_price_cents:price}).eq("id",businessId).eq("organization_id",id).eq("owner_user_id",user.id);if(error)throw new Error(error.message);revalidatePath("/businesses");revalidatePath("/market");}