import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export default async function RolesPage() {
  const supabase = await createClient();
  const { data: org } = await supabase.from("organizations").select("id,name").eq("slug","seaside-rp").maybeSingle();
  const { data: roles } = org ? await supabase.from("organization_roles").select("id,name,description,hierarchy_level,parent_role_id,enabled").eq("organization_id",org.id).order("hierarchy_level",{ascending:false}) : {data:[]};
  return <main className="cad-app"><aside className="sidebar"><Link href="/staff" className="cad-brand"><strong>KIWI</strong><span>CAD</span></Link><div className="server-chip"><span className="online-dot"/><div><small>SERVER</small><b>SeasideRP</b></div></div><p className="side-label">STAFF</p><nav className="side-nav"><Link href="/staff" className="side-link"><i>◆</i><span>Staff</span></Link><Link href="/staff/logs" className="side-link"><i>▤</i><span>Audit Logs</span></Link><Link href="/staff/roles" className="side-link active"><i>◆</i><span>Roles & Permissions</span></Link></nav></aside><section className="workspace"><header className="workspace-top"><div><span className="crumb">KIWI CAD / SEASIDERP / STAFF / ROLES</span><h1>Roles & Permissions</h1></div><Link href="/staff" className="profile-button">Staff</Link></header><div className="content"><section className="panel"><div className="panel-head"><div><span className="panel-kicker">ACCESS CONTROL</span><h3>Organization roles</h3></div><span className="badge green">{roles?.length ?? 0} ROLES</span></div><div className="quick-list">{roles?.map((role:any)=><div key={role.id} style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:20,padding:"15px 0",borderBottom:"1px solid rgba(255,255,255,.06)"}}><div><b>{role.name}</b><small style={{display:"block"}}>{role.description || "Custom organization role"} · Level {role.hierarchy_level}</small></div><span className="badge">{role.enabled ? "ENABLED" : "DISABLED"}</span></div>)}</div><p className="info-copy">Roles support hierarchy and inherited permissions. The next management action is assigning exact permission keys and mapping Discord roles to these CAD roles.</p></section></div></section></main>;
}
